#!/bin/bash
#'dataPath', 'outputPath(for model, images, etc)','instance' , 'fusion-instances','cropSize','fusion-type'
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 1 8_6,9_7,9_5 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 2 7_6,7_5,9_5 17,25,33,41,49,57 1
python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 3 9_7,7_7,8_6 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 4 9_5,8_6,8_7 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 5 7_6,9_6,9_7 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 6 8_6,7_6,9_7 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 7 9_5,7_7,9_6 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 8 8_6,8_7,9_6 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 9 8_6,9_6,7_6 17,25,33,41,49,57 1
#python /media/tensorflow/coffee/applications/all-maps-fusion.py /media/tensorflow/coffee/dataset/ /media/tensorflow/coffee/output/results/probability/ /media/tensorflow/coffee/output/results/maps-fusion/ 10 9_7,7_7,7_6 17,25,33,41,49,57 1
